### ISSUE TITLE
Error : Can't detect your location 

### ISSUE THREAD

**Issue by whereisvinod** [voronianski/realtime-geolocation-demo#2]
In the demo link as well as the download project i am getting the alert of `Error : Can't detect your location`. I installed the modules (socket.io , node-static). How can I fix this issue?

**Comment by voronianski** [comment]
@whereisvinod please look at this

`error code 2: “Can\’t detect your location”, //position unavailable`

##### POSITION_UNAVAILABLE (numeric value 2)*

The position of the device could not be determined. For instance, one or more of the location providers used in the location acquisition process reported an internal error that caused the process to fail entirely.

---

*http://dev.w3.org/geo/api/spec-source.html#position_error_interface
